<a href="https://colab.research.google.com/github/1uch0/ML_Course_training/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [20]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [21]:
#It will print the current version of tensowrflow
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [22]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #Matrix of features X, THE FIRST 3 ROWS ARE UNNECESARY SO WE CAN TAKE THEM OUT. NUMBER, ID, SURNAME HAS NP IMPACT IN THE DEPEDNET VARIABLE
y = dataset.iloc[:, -1].values



In [23]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [24]:
print(y) ##All the features starting from the credit Score
##We need to encode somre of the categortical data

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#We take all the rows until index 2
X[:, 2] = le.fit_transform(X[:, 2])

In [26]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#We just replace the number of the column we want to encode, in this case is the second columns so we put number 1....."OneHotEncoder(), [1])]"
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X)) #uPDATE THE new matrix if features X, and in np array format

In [28]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [30]:
##It is abolsolutaly compulsory in deep learning for training set and test set


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [31]:
#ANN is a sequence of layers
#Creates an ann variable that represent a neural network as a sequence of layers
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [32]:
##add method in nn. to add anything: hidden layer, dropout layer
##.Dense() number of hidden neurons we want to have
##How do we know many neurons we have....JUST EXPERIMENTATION. With hyperparameters

##activation='relu' activaction function, rectifier function

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [33]:
#just copy previous line of code

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [34]:
##Two parameters should be changed
##Since we want to predict a binary value. here we need to put 1 neuron of output
#if it was a classfication problem with 3 would need 3 neurons
##Sigmoid actovation function. It will give also the probability that the binary output is 0/1
#activstion should be softmax for categorical classifcaition

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [35]:
#We could have various parameters: optimizer, loss, and hte matrix. Choose several matrix to evaluate several metrics at the same time.
##optimzier one that can perform stochastic gradient descent. It is what will update the weights in oider to reduces the losss errors comapred predictction to the real results.
##Adam optimzer is a good suggestion

##Loss way ot compare difference between the precirion and the real results.
##non ninaary classifcation the loss should be categortical_crossentropy
#here it is binary classifcaition
#Metrics that we need to evaluate the accuracy


ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


### Training the ANN on the Training set

In [36]:
##method to train your NN
##Classic value of the batsch size that is usually chosen is 32
##Number of epochs

##Epochs the  number of times you pass the data trought the model

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7847 - loss: 0.5479
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8051 - loss: 0.4521
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8013 - loss: 0.4482
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8089 - loss: 0.4328
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8168 - loss: 0.4247
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8144 - loss: 0.4285
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8161 - loss: 0.4279
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8270 - loss: 0.4127
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8328 - loss: 0.4086
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8281 - loss: 0.4114
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8347 - loss: 0.3991
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [53]:
# Combine these into a single list representing the features of the observation:

#Be carefully with the dummy variable. France is not anymore the string France it is the 0,0,1

# Also we need to take care with the scaling
single_observation = [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]

# Call the transform method with the input data and then pass the scaled data to predict.
print(ann.predict(sc.transform(single_observation)))

#theshold of 0.5 so that we get True/False value
print(ann.predict(sc.transform(single_observation))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0.02082396]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [54]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 201  204]]


0.8635