<a href="https://colab.research.google.com/github/1uch0/ML_Course_training/blob/main/artificial_neural_network_regression_to_predoct_Energy_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [26]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [27]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [36]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
print(X)
y = dataset.iloc[:,-1].values # We are selecting just the last column
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [38]:
#ANN as a sequence of layers
#Tensorflow allow us to build NN

#We get acces to the sequential class
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [39]:
#Dense class the connection with the first layer with the first hidden layer
#Once we input the partmeters of training the number of the first layer will be automatically recognized
#We just added the fist hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the second hidden layer

In [40]:
#Now I have added the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the output layer

In [41]:
#Output layer has to change to 1 as there is just one output
#For regression nneds to remove activation functiom
#Sigmoid for classification
#Softmax for classification of more than 2

ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [42]:
#Connecting optimiser loss funcion and ANN
#Optimser_: toool to perfomr stochastic gradient descent
#First backgropagation, then backward propagation

ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [43]:
ann.fit(X_train, y_train, batch_size = 32,epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 101362.4219
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 160.2052
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 148.3408
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 145.1241
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 136.8205
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 130.6350
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 118.4691
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 110.7286
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96.1212
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 85.4275
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 83.6903
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 74.6756
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 69.7565
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 63.7197
Epoch 15/100
240/2

### Predicting the results of the Test set

In [47]:
y_pred = ann.predict(X_test)

#set the maximum number of decimals to 2
np.set_printoptions(precision=2)

#Put the 2 vectors together to compare them


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [51]:
#Reshape y because it is horizontal vector. I want to convert o a vertical one
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis=1))

#We can see 2 vectors first one vector of predictions and the second one vreal data

[[431.91 431.23]
 [462.88 460.01]
 [466.36 461.14]
 ...
 [473.59 473.26]
 [440.46 438.  ]
 [459.61 463.28]]
