<a href="https://colab.research.google.com/github/1uch0/ML_Course_training/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np # library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices
import matplotlib.pyplot as plt #creating static, animated, and interactive visualizations. It is widely used in data analysis,
import pandas as pd #Python library for data analysis and manipulation. It provides flexible data structures, primarily Series (1D arrays) and DataFrame (2D tables)

## Importing the dataset

In [10]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values #Extract all the columns in the datse except the last one
y = dataset.iloc[:, -1].values #Usually in the datasets the last column is the dependet variable, output. In this case we dont want a range. Just the last column

In [11]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [13]:
#Different ways to taling care of missing data
#Firs thing to do is just ignoring the row
#Sklearn


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #Missing values will be replaced by the mean of the colums
imputer.fit(X[:, 1:3]) #Only the ones with categorical values are replaced by the average. Exlucde the non-numrical values
X[:, 1:3] = imputer.transform(X[:, 1:3]) #Tranform method







In [14]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [15]:
#Why categorical data. Change these categories into numbers.
#Country code will be replace by 3 columns with 0s and 1s
#One hot enconding change the gategorical data colums for each caterguy

# Python that provides simple and efficient tools for data mining, analysis, and predictive modeling

#enconding transofrmation, second element the class OneHotEncoder
#The last argument "remainder ='passthrough' is to mantain

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X)) #uPDATE THE new matrix if features X, and in np array format

In [22]:
print(X)
#We can see the that different countries are enconded as differtens 0s and 1s

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [26]:
from sklearn.preprocessing import LabelEncoder #this can be use when we have just 2 variables
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [30]:
#Feature scaling should be applied after slippting splitting data in training set and test set
#Feature scaling prevent diferent types of data have different weights
#Test set is someting you are not suppose to work in the model. We dont want information likage

#train_test_split. For separate sets for trainig and tes. 2x and 2y

#20% observation go to the test set

#Make sure we have same random factors, rando state = 1


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [31]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [32]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [33]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [34]:
print(y_test)

[0 1]


## Feature Scaling

In [37]:
#Feature scaling should be applied after the dvision beteen test set and training set to avoid nformarion kikage
#Avoid some features to be dominaited
#Just apploied for some of the ML models
#Standarisation (values between -3 and +3) and Normalisation(-1 and +1).

#Nomralization when having normal distribution
#Standarizaion. Works always fine

#Standarization just for the training part of the data

#JUST APPLY FEAUTURE SCALING TO THE NUMERICAL VALUES, NOT TO THE DUMMY VARIABKLES (CLASSES), just aged and salary

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])


#We need to apply the same transforation in the same scaler to the test set

X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [39]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578554 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057846 -0.07013167641635404]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022487 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [40]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.4497366439748442 0.20564033932253026]]
